version: "3"
services:
  mongo:
    image: mongo:latest
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    expose:
      - 27017
  backend:
    container_name: brno-PTSAT-be
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3033:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    networks:
      - app-network
  frontend:
    container_name: brno-PTSAT-fe
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    restart: always
    ports:
      - "3034:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge